# Generated by Django 5.2.6 on 2025-11-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Longer context that appears on the profile.'),
        ),
        migrations.AddField(
            model_name='user',
            name='headline',
            field=models.CharField(blank=True, help_text='Optional short descriptor that surfaces on dashboards.', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Optional profile photo used across the UI.', null=True, upload_to='avatars/'),
        ),
    ]
