# Generated by Django 5.2.6 on 2025-10-27 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_remove_material_pdf_material_content_type_and_more'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['owner', 'status'], name='quiz_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['created_at'], name='quiz_created_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz', 'order'], name='qq_quiz_order_idx'),
        ),
    ]
