# Generated by Django 5.2.8 on 2025-11-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='timer_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Optional timer in minutes for the quiz', null=True),
        ),
    ]
