# Generated by Django 5.2.6 on 2025-10-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_quiz_owner_status_idx_quiz_quiz_created_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quiz',
            name='quiz_owner_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='quiz_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='quizquestion',
            name='qq_quiz_order_idx',
        ),
    ]
