# Generated by Django 5.2.8 on 2025-11-08 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0002_remove_material_pdf_material_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(help_text='Lesson content, notes, or plan')),
                ('scheduled_date', models.DateField(blank=True, help_text='Optional scheduled date for this lesson', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, help_text='Optional associated material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='materials.material')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
    ]
