# Generated by Django 5.2.8 on 2025-12-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_scheduled_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
    ]
